version: '3'
services:
  db:
    container_name: postgres
    image: postgres:11
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    ports:
      - "5432:5432"      
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
  backend:
    container_name: backend
    build: ./backend
    command: bash -c "bundle config set path /backend/local_gems && bundle install && bundle exec rails s -p 3000 -b '0.0.0.0'"
    working_dir: /backend
    volumes:
      - ./backend:/backend
    depends_on:
      - db
  frontend:
    container_name: frontend
    image: "node:21-alpine"
    user: "node"
    working_dir: /frontend
    volumes:
      - ./frontend:/frontend
    command: "yarn run dev"
    depends_on:
      - backend
  yaichi:
    container_name: yaichi
    image: mtsmfm/yaichi:1.5.0
    ports:
      - 3000:3000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
